# Generated by Django 3.2.9 on 2022-03-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FASHION', 'Fashion'), ('ELECTRONICS', 'Electroincs'), ('WEB DEVELOPMENT', 'Web Development'), ('ARTS & CRAFTS', 'Arts & Crafts'), ('BOOKS', 'Books'), ('SOFTWARE', 'Software'), ('HOME & KITCHEN', 'Home & Kitchen')], max_length=225),
        ),
    ]
