# Generated by Django 3.2.9 on 2022-09-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220802_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
