# Generated by Django 3.2.9 on 2023-04-05 13:02

import chat.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('PICTURE', 'Picture'), ('VOICE-NOTE', 'Voice-Note'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video')], default='PICTURE', max_length=15)),
                ('media', models.FileField(blank=True, help_text='Files', null=True, upload_to=chat.models.upload_path)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(default='Messages')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('platform', models.CharField(choices=[('IOS', 'Ios'), ('ANDRIOD', 'Android')], default='ANDRIOD', max_length=20)),
                ('token', models.TextField(blank=True, null=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='authentication.userprofile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_user_one', to='authentication.userprofile', verbose_name='User1')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_user_two', to='authentication.userprofile', verbose_name='User2')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('chats', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Messages')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
                ('file', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_chat', to='chat.uploadedfile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='authentication.userprofile', verbose_name='Author')),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['title'], name='chat_notifi_title_31dc92_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['platform'], name='chat_notifi_platfor_5ed004_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user_one', 'user_two'], name='chat_conver_user_on_c0fad4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('user_one', 'user_two')},
        ),
    ]
