# Generated by Django 4.1.3 on 2023-05-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ("-date_created",)},
        ),
    ]
