# Generated by Django 3.2.9 on 2022-06-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='is_verified',
            new_name='is_verified_business',
        ),
    ]
