# Generated by Django 4.1.3 on 2023-05-29 11:09

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="card_back",
            field=models.ImageField(
                blank=True, null=True, upload_to=authentication.models.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="card_front",
            field=models.ImageField(
                blank=True, null=True, upload_to=authentication.models.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="pob",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=authentication.models.upload_to,
                verbose_name="Proof of Business",
            ),
        ),
    ]
