# Generated by Django 3.2.9 on 2022-09-21 06:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_back',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_front',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='pob',
            field=models.URLField(default='', verbose_name='Proof of Business'),
        ),
    ]
