# Generated by Django 3.2.9 on 2022-02-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_superuser',
        ),
    ]
