# Generated by Django 3.2.9 on 2022-02-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220201_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='anon', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
