# Generated by Django 3.2.9 on 2022-09-23 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20220921_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=225, null=True), default=list, size=None),
        ),
    ]
