# Generated by Django 3.2.9 on 2022-09-23 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220923_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, default=list, null=True, size=None),
        ),
    ]
