# Generated by Django 3.2.9 on 2022-08-02 17:08

import authentication.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220802_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_back',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_to_card_back),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_front',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_to_card_front),
        ),
        migrations.AlterField(
            model_name='user',
            name='gallery',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_to_gallery), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='pob',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_to_pob, verbose_name='Proof of business'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='Username', max_length=100, null=True),
        ),
    ]
