# Generated by Django 3.2.9 on 2022-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
