# Generated by Django 3.2.9 on 2022-09-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20220923_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/skill4cash/image/upload/v1/profile/default'),
        ),
    ]
