# Generated by Django 3.2.9 on 2022-09-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_back',
            field=models.URLField(blank=True, default=str, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='card_front',
            field=models.URLField(blank=True, default=str, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pob',
            field=models.URLField(blank=True, default=str, null=True, verbose_name='Proof of Business'),
        ),
    ]
