# Generated by Django 3.2.9 on 2022-09-16 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20220915_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.category'),
        ),
    ]
